### ISSUE TITLE
Release 1.0 SOW

### ISSUE THREAD

**Issue by arsenykonohovwork** [arsenykonohovwork/inspectah-curvaceous#1]
## SOW

- [x] Spike | Stack of technologies #2 
- [x] Concept of application, break down SOW #4 
- [x]  Spike | Concept of application, fill up Acceptance Criteria #3
